### ISSUE TITLE
"Cannot find module 'zod'" in production environment

### ISSUE THREAD

**Issue by oakgary** [openai/openai-node#1072]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

```
Error: Cannot find module 'zod'
Require stack:
- /app/node_modules/openai/_vendor/zod-to-json-schema/parseDef.js
- /app/node_modules/openai/_vendor/zod-to-json-schema/index.js
- /app/node_modules/openai/helpers/zod.js
- /app/main.js
at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
at Module._load (node:internal/modules/cjs/loader:981:27)
at Module.require (node:internal/modules/cjs/loader:1231:19)
at Hook.Module.require (/app/node_modules/dd-trace/packages/dd-trace/src/ritm.js:64:27)
at require (node:internal/modules/helpers:177:18)
at Object.<anonymous> (/app/node_modules/openai/_vendor/zod-to-json-schema/parseDef.js:4:15)
at Module._compile (node:internal/modules/cjs/loader:1364:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
at Module.load (node:internal/modules/cjs/loader:1203:32)
at Module._load (node:internal/modules/cjs/loader:1019:12) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
        '/app/node_modules/openai/_vendor/zod-to-json-schema/parseDef.js',
        '/app/node_modules/openai/_vendor/zod-to-json-schema/index.js',
        '/app/node_modules/openai/helpers/zod.js',
        '/app/main.js'
    ]
}
```

`package.json`:
```
"dependencies": {
	...
	"openai": "^4.60.1",
	"zod": "^3.23.8",
	...
}
```

`npm ls zod` logs
```
@redacted/source@0.0.0 /Users/redacted
├─┬ openai@4.60.1
│ └── zod@3.23.8 deduped
└── zod@3.23.8
```

### To Reproduce

I am not sure to be honest. It works fine locally but seems to break somewhere during the deployment. Please let me know what insights could further help you debug this issue.

### OS

linux/arm64

### Node version

v18.20.4

### Library version

v4.60.1

**Comment by RobertCraigie** [comment]
@oakgary what happens if you import zod in your own code? does that work?

**Comment by oakgary** [comment]
> @oakgary what happens if you import zod in your own code? does that work?

@RobertCraigie the project including openai and zod work entirely fine locally, so I guess yes.

**Comment by oakgary** [comment]
> That's strange, could you share your `package.json`? And you're just using JS?

I can't really share the whole `package.json`. Is there any specific part you are interested in besides the two packages as referenced in the initial post?
Yes, It's just a NestJS application running on NodeJS.

**Comment by RobertCraigie** [comment]
No worries, would you mind redacting any parts you feel are sensitive and then sharing it? I'm not really sure what I'd need to be able to reproduce, so it would be helpful to get as similar of a setup as possible.

**Comment by oakgary** [comment]
There isn't really much left after 
```
{
	"name": "redacted",
	"version": "redacted",
	"license": "redacted",
	"scripts": {
		// redacted
	},
	"private": true,
	"dependencies": {
		// redacted
		"openai": "^4.60.1",
		"zod": "^3.23.8"
	},
	"devDependencies": {
		// redacted
	}
}
```
For context though, we only added `zod` for the `openai` implementation and are not using it for anything else.

During our deployment the relevant GitHub Actions steps should be
```
steps:
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Set Node.js 20.x
    uses: actions/setup-node@v4
    with:
      node-version: 20.x

  - name: Cache node modules
    uses: actions/cache@v3
    with:
      path: node_modules
      key: node_modules-${{hashFiles('yarn.lock')}}
      restore-keys: node_modules-

  - name: Run yarn install
    uses: borales/actions-yarn@v4
    with:
      cmd: install
```

When it's deployed it's running inside a `linux/arm64 node:18-alpine` docker container.
